import re

with open("docs/Collatz_v8_en.tex", "r", encoding="utf-8") as f:
    tex = f.read()

# Replace section 4.3
s43_new = r"""\subsection{Two-Layer Invariants: Core and Adapter Shell}

Previously, it was assumed that \textbf{Zone 2} is characterized by rigid global invariants $d = 259$ and $S = \text{bits} + 271$. A complete census of all 913 inputs reveals a two-layer structure: a strictly identical core and a variable adapter shell.

\textbf{1. The Core ($x^* \to \text{Peak}$).} All 913 numbers pass through $x^*$. The trajectory from $x^*$ to the peak of 140 bits is strictly identical. It has a length of $d_{core} = 251$ odd steps and a cumulative sum of shifts $S_{core} = 336$. The ratio $S_{core}/d_{core} \approx 1.338$ is the true constant of the basin.

\textbf{2. The Adapter Shell.} The numbers reach $x^*$ in $k \in [0, 7]$ odd steps. 
\begin{itemize}
    \item $x^*$ itself has $k=0$ (depth 0). For it, $d = 251$ and $S = 336$.
    \item 378 out of 913 numbers lie at maximum depth $k=7$ (the outer shell). For them, the total path length is $d = 251 + 7 = 258$. 
    \item An affine bit-burning law governs the outer shell ($k=7$): $S_{adapter} = \text{bits} - 63$. Since $S_{total} = S_{core} + S_{adapter} = 336 + \text{bits} - 63$, the invariant $S = \text{bits} + 273$ holds \emph{only} for the outer shell. Every additional bit in the input number costs exactly $+1$ to the sum of shifts in the adapter.
\end{itemize}

Analysis of the adapter prefixes via a deterministic finite automaton yields a growth rate of $\approx 0.395$ bits$^{-1}$, which is close to the topological entropy of the adapters ($\sim 0.486$). The adapter sequence is completely determined by the lowest 19 bits of the input. Thus, \textbf{Zone 2} is an exact $d=251$ core path, dressed in a deterministic pre-image tree."""

# Note: need to escape backslashes in replacement string by either not using it as a raw string in sub, or lambda
tex = re.sub(r'\\subsection\{Invariants of Zone 2\}(.*?)(?=\\subsection\{)', lambda m: s43_new + "\n\n", tex, flags=re.DOTALL)

# Replace section 4.4
s44_new = r"""\subsection{$x^*$ and Windowed Hit Rate}
\label{subsec:x_star_windowed}

We introduce two metrics for a confluence center with respect to a target peak $P$:
\begin{itemize}
    \item \textbf{Completeness:} The fraction of all anomalous numbers with peak $P$ (within a specific bit window) that pass through the center.
    \item \textbf{Purity (Hit Rate):} The fraction of nodes in the reverse tree of the center (at a specific depth and within a bit window) that actually reach peak $P$, rather than escaping to higher peaks.
\end{itemize}

Early measurements yielded a 100\% Hit Rate for \textbf{Class A} centers ($121$ and $x^*$). However, expanding the reverse tree to depth 8 reveals the phenomenon of \emph{parasitic branches}.

\begin{table}[h]
\centering
\begin{tabular}{lll}
\toprule
\textbf{Depth} & \textbf{Center 121 (Peak 14)} & \textbf{Center $x^*$ (Peak 140)} \\
\midrule
3 & 75.0\% & 100.0\% \\
5 & 62.5\% & 99.7\% \\
7 & 69.2\% & 90.6\% \\
8 & 88.2\% & 99.0\% \\
\bottomrule
\end{tabular}
\caption{Purity (Hit Rate) of Class A centers measured in the bit window $[P/2, P)$.}
\end{table}

The drop in purity at depth 7 is a physical consequence of the finite bit window: nodes with bit lengths close to $P$ are forced to ``burn'' bits via massive initial shifts. If they fail to do so, the multiplication by 3 pushes their trajectory above the target peak before they even enter the core path, creating a parasitic branch. 

Thus, a 100\% Hit Rate is not a global property of \textbf{Class A}. Instead, \textbf{Class A} is defined by an extreme \emph{density of coverage}: the ability to maintain $>90\%$ purity even at depth 7 (where the tree for $x^*$ contains over a million nodes), coupled with a deep path ($d_{peak} > 20$) and a high shift density ($S/d > 1.30$)."""

tex = re.sub(r'\\subsection\{\$x\^\*\$ as a Narrow Gate\}(.*?)(?=\\section\{)', lambda m: s44_new + "\n\n", tex, flags=re.DOTALL)

# Insert section 4.6
s46_new = r"""\subsection{Grammar of the Critical Tail}

A spectral analysis of the shift-vectors for all 913 inputs reveals that the trajectory of \textbf{Zone 2} is not a sequence of independent shifts, but a hierarchical symbolic grammar generated by a Hidden Markov Model (HMM). 

The final 90 steps (the critical tail) are strictly periodic across the entire ensemble. Autocorrelation confirms a dominant period of $T \approx 6.3$ and $T \approx 18$:
\begin{enumerate}
    \item \textbf{The $T=18$ Clock:} Deep dips (shifts $a \ge 3$) are phase-locked. For all 913 inputs, the distance from the end of the trajectory to any deep dip modulo 18 is exactly 0, 5, or 9. The clock is perfectly synchronized across the entire basin.
    \item \textbf{The [2,1,1] Finisher:} The motifs $[2,1,1]$ and $[2,1,2,1,1,1]$ are heavily overrepresented in the tail compared to a shuffled control. The tail acts as a coherent unit with $S/d = 4/3 \approx 1.333$, shadowing the 2-adic periodic point $-29/11$.
\end{enumerate}

Any mutation to this $[2,1,1]$ finisher destroys the phase alignment, forcing the trajectory to miss the peak. This extreme fragility ($\sim 0.7$ bits of entropy) explains the ``dead zone'': evolutionary searches fail because the structural cylinder of the target is exponentially narrow."""

# insert before Section 5
tex = re.sub(r'(?=\\section\{Confluence Archipelago)', lambda m: s46_new + "\n\n", tex)


with open("docs/Collatz_v8_en_edited.tex", "w", encoding="utf-8") as f:
    f.write(tex)

print("Wrote edited tex")
