"""
Experiment F: Adelic Equidistribution
Probes the intersection of R, Z_2, and Z_3 by tracking the joint distribution
of (log2(N) mod 1, N mod 2^m, N mod 3^n) along long Collatz orbits.
"""

import numpy as np
from scipy import stats
import time
import math

def collatz_orbit_odd(N, max_steps):
    """Returns a list of odd numbers in the Collatz orbit."""
    orb = []
    x = N
    for _ in range(max_steps):
        if x % 2 == 0:
            x //= 2
        else:
            orb.append(x)
            x = 3 * x + 1
            if x == 4: # prevent cycle
                break
    return orb

def analyze_equidistribution(orb, m, n):
    """
    Tests if frac(log2 N) is uniformly distributed on [0,1)
    AND if it is independent of (N mod 2^m) and (N mod 3^n).
    """
    fracs = []
    y_vals = []
    z_vals = []
    
    mod2 = 2**m
    mod3 = 3**n
    
    for val in orb:
        fracs.append(math.log2(float(val)) % 1.0)
        y_vals.append(val % mod2)
        z_vals.append(val % mod3)
        
    fracs = np.array(fracs)
    y_vals = np.array(y_vals)
    z_vals = np.array(z_vals)
    
    # 1. Global Uniformity (KS Test against Uniform(0,1))
    ks_stat, p_val = stats.kstest(fracs, 'uniform')
    print(f"Global Uniformity of frac(log2 N):")
    print(f"  KS statistic = {ks_stat:.4f}, p-value = {p_val:.2e}")
    if p_val < 0.01:
        print("  -> REJECTED global uniformity (significant structure!)")
    else:
        print("  -> ACCEPTED global uniformity")
        
    # 2. Conditional Uniformity
    # We group by the cross-product of valid states
    # For odd numbers, y is odd.
    # For z mod 3^n, if N is odd and generated by 3x+1, it's rarely 0 mod 3.
    # We just group by (y, z) and check means
    
    states = {}
    for i in range(len(orb)):
        state = (y_vals[i], z_vals[i])
        if state not in states:
            states[state] = []
        states[state].append(fracs[i])
        
    print(f"\nConditional Means E[frac(log2 N) | N mod 2^{m}, N mod 3^{n}]:")
    print(f"{'y (mod 2^m)':>12} | {'z (mod 3^n)':>12} | {'Count':>8} | {'Mean frac':>12} | {'KS p-val':>10}")
    print("-" * 65)
    
    # Sort states by count to show the most visited ones
    sorted_states = sorted(states.items(), key=lambda item: len(item[1]), reverse=True)
    
    for state, vals in sorted_states[:20]:  # show top 20
        y, z = state
        count = len(vals)
        if count < 10:
            continue
        mean_val = np.mean(vals)
        _, p = stats.kstest(vals, 'uniform')
        print(f"{y:12d} | {z:12d} | {count:8d} | {mean_val:12.4f} | {p:10.2e}")

def main():
    print("Experiment F: Adelic Equidistribution Diagnostic\n")
    
    # Generate a long orbit. 
    # To get a lot of data, we can start with a massive number or concatenate several.
    # Let's concatenate orbits of a few large seeds to get ~10^6 points.
    
    import random
    random.seed(42)
    seeds = [random.randint(2**100, 2**101) for _ in range(100)]
    
    print("Generating orbits...")
    t0 = time.time()
    full_orb = []
    for s in seeds:
        # get up to 5000 odd steps per seed
        full_orb.extend(collatz_orbit_odd(int(s), 5000))
        
    print(f"Total odd points collected: {len(full_orb)} (took {time.time()-t0:.2f}s)")
    print()
    
    m = 3 # mod 8
    n = 2 # mod 9
    analyze_equidistribution(full_orb, m, n)

if __name__ == "__main__":
    main()
